export const pageResource = {
  VI: {
    message: {
      employeeCodeEmpty: "Mã nhân viên không được để trống",
      departmentEmpty: "Phòng ban không được để trống",
      employeeNameEmpty: "Tên nhân viên không được để trống",
      emailNotValid: "Email không hợp lệ",
      dobNotValid: "Ngày sinh không được lớn hơn ngày hiện tại",
      questionForDelete: "",
    },
    textButton: {
      btnDetailEmployee: "Thêm nhân viên mới",
      btnStorage: "Cất",
      btnStorageAndAdd: "Cất và thêm",
      btnCancel: "Hủy",
      btnConfirm: "Xác nhận",
      btnEdit: "Sửa",
      btnClose: "Đóng",
      btnConfirmYes: "Có",
      btnConfirmNo: "Không",
      btnRefreshText: "Lấy lại dữ liệu",
      btnExportExcel: "Xuất ra excel",
    },
    placehoderText: {
      descriptionInputField: "Tìm theo mã, tên nhân viên",
    },
    tableHeader: {
      employeeCode: "MÃ NHÂN VIÊN",
      employeeName: "TÊN NHÂN VIÊN",
      gender: "GIỚI TÍNH",
      dob: "NGÀY SINH",
      identityNumber: "SỐ CMND",
      position: "CHỨC DANH",
      departmentName: "TÊN ĐƠN VỊ",
      bankAccountNumber: "SỐ TÀI KHOẢN",
      bankName: "TÊN NGÂN HÀNG",
      branchName: "CHI NHÁNH TK NGÂN HÀNG",
    },
    gender: {
      female: "Nữ",
      male: "Nam",
      other: "Khác",
    },
    formLabels: {
      code: "Mã",
      name: "Tên",
      department: "Đơn vị",
      position: "Chức danh",
      dob: "Ngày sinh",
      gender: "Giới tính",
      identityNumber: "Số CMND",
      identityDate: "Ngày cấp",
      identityPlace: "Nới cấp",
      address: "Địa chỉ",
      phoneNumber: "ĐT di động",
      telephoneNumber: "ĐT cố định",
      email: "email",
      bankAccountName: "Tài khoản ngân hàng",
      bankName: "Tên ngân hàng",
      branch: "Chi nhánh",
    },
    header: {
      titleEmployeePage: "Nhân viên",
      dialogEmployeeTitle: "Thông tin nhân viên",
    },
    navbarText: {
      overview: "Tổng quan",
      employee: "Nhân viên",
      cast: "Tiền mặt",
      deposits: "Tiền gửi",
      buy: "Mua hàng",
      sell: "Bán hàng",
      bill: "Quản lí hóa đơn",
      warehouse: "Kho",
      tool: "Công cụ dụng cụ",
      asset: "Tài sản cố định",
      tax: "Thuế",
      price: "Giá thành",
      general: "Tổng hợp",
      budget: "Ngân sách",
      report: "Báo cáo",
      analysis: "Phân tích tài chính",
    },
    others: {
      brandName: "Công ty TNHH SONG VIỆT",
      customerName: "Đinh Sĩ Thủy",
    },
  },
  EN: {},
};
